name: dj_fc
description: Auto-Generate corresponding Dj Widgets for Flutter Widgets given Flutter SDK location.
version: 0.0.0
homepage: https://www.ark4579.com
repository: https://github.com/ARK4579/dj_fc
issue_tracker: https://github.com/ARK4579/dj_fc/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dj: 0.0.9

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
