name: dj_fc
description: Auto-Generate corresponding Dj Widgets for Flutter Widgets given Flutter SDK location.
version: 0.0.1
homepage: https://www.ark4579.com
repository: https://github.com/ARK4579/dj_fc
issue_tracker: https://github.com/ARK4579/dj_fc/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.0.0
  args: ^2.1.0
  dj_io: 0.0.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
